version: '3'
services:
  service-postgres:
    image: postgres
    restart: always
    container_name: service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    networks:
      - anima-network

  service-rabbitmq:
    container_name: service-rabbitmq
    image: rabbitmq
    restart: always
    ports:
      - 56721:5672
    networks:
      - anima-network

  service-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: service-api
    restart: always
    ports:
      - 5100:5100 
    depends_on:
      - service-postgres 
      - service-identity 
    networks:
      - anima-network

  service-identity:
    build:
      context: ./identity
      dockerfile: Dockerfile
    container_name: service-identity
    restart: always
    ports:
      - 5200:5200
    networks:
      - anima-network

  service-consumer:
    build:
      context: ./console-consumer
      dockerfile: Dockerfile
    container_name: service-consumer
    restart: always
    ports:
      - 5300:5300 
    depends_on:
      - service-rabbitmq 
    networks:
      - anima-network

  service-boleto:
    build:
      context: ./boleto-api
      dockerfile: Dockerfile
    container_name: service-boleto
    restart: always
    ports:
      - 5400:5400 
    networks:
      - anima-network

  service-academico:
    build:
      context: ./secretaria-academica
      dockerfile: Dockerfile
    container_name: service-academico
    restart: always
  depends_on:
      - service-postgres 
    ports:
      - 5600:5600 
    networks:
      - anima-network
 
  service-inscricao:
    build:
      context: ./inscricao-upskilling/inscricao-upskilling
      dockerfile: Dockerfile
    container_name: service-inscricao
    restart: always
    depends_on:
      - service-postgres 
    ports:
      - 5700:5700 
    networks:
      - anima-network
 
  service-aluno:
    build:
      context: ./area-do-aluno-upskilling
      dockerfile: Dockerfile
    container_name: service-aluno
    restart: always
    depends_on:
      - service-postgres 
      - service-identity 
      - service-api
    ports:
      - 5800:5800 
    networks:
      - anima-network

volumes:
  postgres_data:

networks: 
  anima-network:
    driver: bridge